baseurl = "https://jamesphare.org/"
languageCode = "en-us"
title = "jamesphare.org"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Writing & Editing"
    url = "/writing-editing/"
    weight = 2
[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 3
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 5
[[menu.main]]
    name = "CV"
    url = "/resume/"
    weight = 6

[params]
    description = "James P. Hare's personal website"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

