baseurl: https://jamesphare.org/
languageCode: en-us
title: James P. Hare
theme: blackburn
author: Yoshiharu Yamashita
copyright: '&copy; 2021. <a href=https://creativecommons.org/licenses/by-sa/4.0/>CC BY-SA</a>'
canonifyurls: yes
paginate: 10
indexes:
  tag: tags
  topic: topics
params:
  brand: jamesphare.org
  dateFormat: 02 Jan 2006
  disqus:
  googleAnalytics: "UA-175878886-1"
  highlightjs: androidstudio
  subtitle:
menu:
  main:
    - identifier: home
      name: Home
      pre: <i class='fa fa-home fa-fw'></i>
      url: /
      weight: 1
    - identifier: post
      name: Posts
      pre: <i class='fa fa-list fa-fw'></i>
      url: /post/
      weight: 2
    - identifier: about
      name: About
      pre: <i class='fa fa-user fa-fw'></i>
      url: /about/
      weight: 3
    - name: Writing
      pre: <i class='fa fa-pen fa-fw'></i>
      url: /writing-editing/
      weight: 4
    - name: Research
      pre: <i class='fa fa-book fa-fw'></i>
      url: /research/
      weight: 5
    - name: Email
      pre: <i class='fa fa-envelope fa-envelope'></i>
      url: mailto:james@jamesphare.org
      weight: 6
social:
  github: jamesphare
  linkedin: jphare
  twitter: mousyaesthete

markup:
  goldmark:
    renderer:
      unsafe: true
